Repository chas-academy/Cobalt-client, pull requests merged in 2018-05, with the labels that each got.

#129 Component: ButtonLink closes #128
  src/Components/Header.js
  src/Elements/ButtonLink.js
  src/stories/Elements/ButtonLink.js
  src/stories/index.js
Labels: review

#135 112 feature/require auth. Closes #112
  src/Components/RequireAuth.js
  src/Containers/App.js
Labels: feature, review

#136 Fix HOC bug
  src/Containers/App.js
Labels: review

#139 137-bug/CopyTextField
  src/Elements/CopyTextfield.js
Labels: review

#141 Revert "137-bug/CopyTextField"
  src/Elements/CopyTextfield.js
Labels: review

#130 124 feature/connect signup
  src/Components/SignUpForm.js
  src/Views/SignUp.js
  src/redux/auth/actions.js
  src/redux/signup/actions.js
  src/redux/signup/constants.js
  src/redux/signup/signupReducer.js
  src/redux/utils/utils.js
Labels: review

#143 Refactor: Create Session Setup with redux closes #131
  src/Components/CreateSession/Preferences.js
  src/Components/Wizard.js
  src/Views/CreateSession.js
  src/Views/Dashboard/Dashboard.js
  src/redux/index.js
  src/redux/session/actions.js
  src/redux/session/constants.js
  src/redux/session/sessionReducer.js
Labels: review

#145 Fixes/signup redirect copytextfield
  src/Components/Header.js
  src/Components/LoginForm.js
  src/Components/RequireAuth.js
  src/Components/SignUpForm.js
  src/Containers/PublicRoot.js
  src/Elements/CopyTextfield.js
  src/Elements/Input.js
  src/Views/Login.js
  src/Views/SignUp.js
  src/redux/index.js
  src/redux/signup/signupReducer.js
Labels: review

#151 update wizard to match new endpoint
  src/Views/CreateSession.js
  src/redux/session/actions.js
  src/redux/session/sessionReducer.js
Labels: review

#152 83-feature/livesessionhost
  src/Components/Modal.js
  src/Components/WithSocket.js
  src/Containers/App.js
  src/Elements/Button.js
  src/Elements/ButtonLink.js
  src/Elements/CopyTextfield.js
  src/Views/LiveSessionHost/EndSession.js
  src/Views/LiveSessionHost/Engagement.js
  src/Views/LiveSessionHost/LiveSessionHost.js
  src/Views/LiveSessionHost/Lobby.js
  src/Views/LiveSessionHost/Paused.js
  src/Views/LiveSessionHost/Summary.js
  src/Views/LiveSessionHost/Timer.js
  src/Views/LiveSessionHost/Warning.js
  src/index.css
Labels: Epic, feature, review

#123 Component: Notifications closes #46
  src/Components/Notifications.js
  src/Components/RequireAuth.js
  src/Containers/App.js
  src/Elements/Notification.js
  src/index.css
  src/redux/index.js
  src/redux/notifications/actions.js
  src/redux/notifications/constants.js
  src/redux/notifications/notificationsReducer.js
  src/stories/Components/Notifications.js
  src/stories/index.js
Labels: review

#155 feature/vote component this closes #121, #84
  public/index.html
  src/Components/VoteSlider.js
  src/Containers/App.js
  src/Views/Client.js
  src/index.css
  src/stories/Components/VoteSlider.js
  src/stories/index.js
Labels: review

#156 153 feature/session owner
  src/Components/WithSocket.js
Labels: review

#157 fix bug where modal for ended session didn't show when session was pa…
  src/Views/Client.js
Labels: review

#159 fixed bug where copy text field got wrong url
  src/Components/CreateSession/SessionStarted.js
  src/Elements/CopyTextfield.js
  src/Views/LiveSessionHost/LiveSessionHost.js
  src/Views/LiveSessionHost/Lobby.js
Labels: review

#158 150-feature/dashboard fetch info
  src/Components/Navigation.js
  src/Components/SessionItem.js
  src/Containers/App.js
  src/Views/Dashboard/Dashboard.js
  src/Views/Dashboard/Sessions.js
  src/redux/index.js
  src/redux/user/actions.js
  src/redux/user/constants.js
  src/redux/user/userReducer.js
Labels: review

#161 Fixes button margin on join session
  src/Components/JoinSession.js
Labels: review

#164 Fix warning not appearing. Add redirect on socket connect fail
  src/Components/WithSocket.js
  src/Views/LiveSessionHost/LiveSessionHost.js
Labels: bug, review

#165 Feature/deployment
  .gitignore
  Dockerfile.prod
  conf/conf.d/default.conf
  docker-stack-dev.yml
  docker-stack-production.yml
  docker-stack-staging.yml
  yarn.lock
Labels: review

#167 Bugfix: protected routes
  src/Containers/App.js
Labels: review

#113 92 feature/profile component
  src/Components/Profile.js
  src/Elements/Avatar.js
  src/Views/Dashboard/Dashboard.js
  src/Views/Dashboard/Profile.js
Labels: review

#174 Bugfix: Notifications
  src/Components/Notifications.js
Labels: review

#172 Enhancement: NotFound Button
  src/Views/NotFound.js
Labels: review

#173 121 feature/vote component
  src/Views/Client.js
Labels: review

#177 Enhancement: Pricing Area
  src/Components/SubscriptionCard.js
  src/Containers/App.js
  src/Views/PricingArea.js
Labels: review

#179 Revert "Enhancement: Pricing Area"
  src/Components/SubscriptionCard.js
  src/Containers/App.js
  src/Views/PricingArea.js
Labels: review

#184 update readme.md with instructions for releases
  README.md
Labels: review

#182 enhancement/responsive signup signin
  package.json
  src/Components/Footer.js
  src/Components/Header.js
  src/Components/JoinSession.js
  src/Components/LoginForm.js
  src/Components/SignUpForm.js
  src/Elements/Button.js
  src/Elements/ButtonLink.js
  src/Views/LandingPage.js
  src/Views/Login.js
  src/Views/SignUp.js
  yarn.lock
Labels: review

#198 add presentations to workspace modal
  src/Views/Dashboard/Workspaces.js
  src/Views/Dashboard/Workspaces/Overview.js
  src/Views/Dashboard/Workspaces/Presentations.js
Labels: review

#176 144 feature/session graph
  package.json
  src/Components/SessionGraph.js
  src/Elements/Tooltip.js
  src/stories/Components/SessionGraph.js
  src/stories/Components/data.json
  src/stories/index.js
Labels: review

#202 Logout
  src/Components/Navigation.js
  src/Views/Dashboard/Dashboard.js
  src/redux/auth/actions.js
  src/redux/auth/authReducer.js
  src/redux/auth/constants.js
  src/redux/notifications/notificationsReducer.js
Labels: review

#207 150 feature/improve dashboard
  src/Components/Navigation.js
  src/Components/SessionItem.js
  src/Components/Wizard.js
  src/Elements/Badge.js
  src/Elements/Card.js
  src/Elements/Heading.js
  src/Elements/Icon.js
  src/Views/Dashboard/Dashboard.js
  src/Views/Dashboard/Sessions.js
  src/redux/session/actions.js
  src/redux/session/constants.js
  src/redux/session/sessionReducer.js
  src/redux/user/userReducer.js
Labels: enhancement, feature

#209 191 feature/slide in menu
  src/Components/NavigationMobile.js
  src/Elements/Icon.js
  src/Views/Dashboard/Dashboard.js
Labels: enhancement, feature

#215 feature/connect workspaces to backend
  src/Components/AddMember.js
  src/Components/Notifications.js
  src/Containers/App.js
  src/Views/Dashboard/Workspaces.js
  src/Views/Dashboard/Workspaces/Members.js
  src/Views/Dashboard/Workspaces/Overview.js
  src/Views/Dashboard/Workspaces/Presentations.js
  src/Views/SignUp.js
  src/redux/index.js
  src/redux/notifications/notificationsReducer.js
  src/redux/user/actions.js
  src/redux/user/userReducer.js
  src/redux/utils/utils.js
  src/redux/workspace/actions.js
  src/redux/workspace/constants.js
  src/redux/workspace/workspaceReducer.js
Labels: review

#214 Enhancement: Notification
  src/Components/Notifications.js
  src/Elements/Notification.js
Labels: review

#227 223 bugfix/private routes
  src/Containers/App.js
  src/redux/auth/actions.js
Labels: review

#234 Epic/workspaces
  src/Components/AddMember.js
  src/Components/Modal.js
  src/Components/Notifications.js
  src/Containers/App.js
  src/Elements/Card.js
  src/Views/Dashboard/Dashboard.js
  src/Views/Dashboard/Workspaces.js
  src/Views/Dashboard/Workspaces/Members.js
  src/Views/Dashboard/Workspaces/Overview.js
  src/Views/Dashboard/Workspaces/Presentations.js
  src/Views/SignUp.js
  src/Views/UpgradePlan.js
  src/index.css
  src/redux/index.js
  src/redux/notifications/notificationsReducer.js
  src/redux/user/actions.js
  src/redux/user/userReducer.js
  src/redux/utils/utils.js
  src/redux/workspace/actions.js
  src/redux/workspace/constants.js
  src/redux/workspace/workspaceReducer.js
Labels: review

#235 219 enhancement/modalclose newsession
  src/Components/Modal.js
  src/Components/Wizard.js
  src/Views/Client.js
  src/Views/CreateSession.js
Labels: review

#203 Removed things that is not used
  src/Components/CreateSession/Preferences.js
  src/Components/Navigation.js
Labels: review

#265 removed hover state from mobile nav-sidebar
  src/Components/NavigationMobile.js
Labels: review

#264 Bugfix: Create new workspace modal not closing
  src/Views/UpgradePlan.js
Labels: review

#262 Bugfix: Modal
  src/Components/Modal.js
Labels: review

#246 add mobile responsiveness to notifications
  src/Components/Notifications.js
Labels: review

#261 Bugfix: session has ended
  src/Views/Client.js
Labels: review

#268 Adds fetch request towards API to verify session exists/ended
  src/Views/Client.js
Labels: review

#263 218 enhancement/rerender sessions on delete
  src/Views/Dashboard/Sessions.js
  src/redux/notifications/notificationsReducer.js
  src/redux/session/actions.js
Labels: review

#271 Removed links that is not used
  src/Components/Footer.js
  src/Components/Header.js
Labels: review

#270 Removed workspacebutton
  src/Components/NavigationMobile.js
  src/Views/Dashboard/Dashboard.js
Labels: review

#269 Add about page
  src/Components/About.js
  src/Containers/App.js
  src/Views/AboutPage.js
Labels: review

#241 add cooldown timer
  src/Components/VoteSlider.js
Labels: review

#242 190 feature/pages contact
  src/Components/ContactForm.js
  src/Containers/App.js
  src/Elements/Icon.js
  src/Elements/Textarea.js
  src/Views/Contact.js
  src/stories/Elements/Icon.js
Labels: review

#273 223 feature/view summary. Closes #233 #255
  package.json
  src/Components/SessionGraph.js
  src/Components/WithSocket.js
  src/Containers/App.js
  src/Views/Client.js
  src/Views/LiveSessionHost/EndSession.js
  src/Views/LiveSessionHost/Summary.js
  src/Views/LiveSessionHost/Timer.js
  src/redux/session/actions.js
  src/redux/session/constants.js
  src/redux/session/sessionReducer.js
  src/redux/user/actions.js
Labels: review

#278 274 bugfix/summary session data undefined. Closes #274 #277 #245
  src/Components/WithSocket.js
  src/Views/LiveSessionHost/Summary.js
Labels: bug

#276 258 enhancement/error cleanup
  src/Components/AddMember.js
  src/Components/ContactForm.js
  src/Components/CreateSession/Preferences.js
  src/Components/CreateSession/SessionStarted.js
  src/Components/Developers.js
  src/Components/Footer.js
  src/Components/Header.js
  src/Components/JoinSession.js
  src/Components/LoginForm.js
  src/Components/Modal.js
  src/Components/Notifications.js
  src/Components/Profile.js
  src/Components/QrCodeWindow.js
  src/Components/SessionGraph.js
  src/Components/SessionItem.js
  src/Components/SubscriptionCard.js
  src/Components/VoteSlider.js
  src/Components/WithSocket.js
  src/Components/Wizard.js
  src/Containers/App.js
  src/Containers/PublicRoot.js
  src/Elements/Balloon.js
  src/Elements/Card.js
  src/Elements/CopyTextfield.js
  src/Elements/Icon.js
  src/Views/Client.js
  src/Views/Contact.js
  src/Views/CreateSession.js
  src/Views/Dashboard/Dashboard.js
  src/Views/Dashboard/Sessions.js
  src/Views/Dashboard/Workspaces.js
  src/Views/Dashboard/Workspaces/Members.js
  src/Views/Dashboard/Workspaces/Overview.js
  src/Views/Dashboard/Workspaces/Presentations.js
  src/Views/LiveSessionHost/EndSession.js
  src/Views/LiveSessionHost/LiveSessionHost.js
  src/Views/LiveSessionHost/Summary.js
  src/Views/LiveSessionHost/Timer.js
  src/Views/SignUp.js
  src/Views/UpgradePlan.js
  src/redux/session/actions.js
  src/redux/session/sessionReducer.js
Labels: review

#279 Fixes previous merge conflict commit
  src/Views/CreateSession.js
Labels: review

#284 enhancement/messages update user
  src/redux/notifications/notificationsReducer.js
  src/redux/user/userReducer.js
Labels: review

#293 Add check on values and removed autocomplete
  src/Components/Profile.js
  src/Views/Dashboard/Profile.js
Labels: review

#295 Fix issue where timer would not restart after resuming post disconnect. Fixes #245
  src/Components/WithSocket.js
Labels: bug

#296 Show correct engagement values when connecting to session. Closes #247
  src/Views/LiveSessionHost/LiveSessionHost.js
  src/Views/LiveSessionHost/Warning.js
Labels: review

#297 Checks all workspaces for presentations
  src/Views/Dashboard/Sessions.js
Labels: review

#298 Session Cards: Go to lobby/ Go to summary
  src/Views/Dashboard/Sessions.js
Labels: review

#307 303 enhancement/update profilestyleing
  src/Components/Profile.js
  src/Containers/App.js
  src/Views/PricingArea.js
Labels: review

#309 Added media query for developers page on mobile
  src/Components/Developers.js
Labels: review
