Repository chas-academy/Cobalt-client, pull requests merged in 2018-04, with the labels that each got.

#9 added storybook and component for heading
  src/Elements/Heading.js
  src/stories/Elements/Heading.js
  src/stories/index.js
Labels: review

#10 Add Avatar component and corresponding element to storybook - closes #5
  src/Elements/Avatar.js
  src/stories/Elements/Avatar.js
  src/stories/index.js
Labels: review

#13 resolved whole theme being added to heading rather than only color - closes chas-academy/Cobalt-client#2
  src/Elements/Heading.js
Labels: review

#12 closes #6 Add input.js and corresponding component in src/stories, update withStyles.js
  src/Elements/Input.js
  src/assets/reset.css
  src/stories/Elements/Input.js
  src/stories/index.js
  src/withStyles.js
Labels: review

#11 Basic component: Paragraph
  src/Elements/Paragraph.js
  src/stories/Elements/Paragraph.js
  src/stories/index.js
Labels: review

#14 closes #7
  src/Elements/FlexContainer.js
Labels: review

#16 It's friday time for that deploy
  src/Elements/Avatar.js
  src/Elements/FlexContainer.js
  src/Elements/Heading.js
  src/Elements/Input.js
  src/Elements/Paragraph.js
  src/assets/reset.css
  src/index.css
  src/stories/Elements/Avatar.js
  src/stories/Elements/Heading.js
  src/stories/Elements/Input.js
  src/stories/Elements/Paragraph.js
  src/stories/index.js
  src/withStyles.js
Labels: review

#15 Revert "closes #7"
  src/Elements/FlexContainer.js
Labels: review

#30 3 feature/button component
  src/Elements/Button.js
  src/stories/Elements/Button.js
  src/stories/index.js
  src/withStyles.js
Labels: enhancement, review

#32 Updates color prop to appearance/withStyles
  src/Elements/Avatar.js
  src/Elements/Heading.js
  src/Elements/Input.js
  src/Elements/Paragraph.js
  src/stories/Elements/Heading.js
  src/stories/Elements/Input.js
Labels: review

#23 Update Dockerfile
  Dockerfile
  src/Elements/FlexContainer.js
Labels: hotfix, review

#31 36 feature/notification
  src/Elements/Notification.js
  src/stories/Elements/Notification.js
  src/stories/index.js
Labels: review

#24 Basic component: Checkbox closes #22
  src/Elements/Checkbox.js
  src/stories/Elements/Checkbox.js
  src/stories/index.js
Labels: review

#36 add card component and storybook closes #28
  src/Elements/Card.js
  src/stories/Elements/Card.js
  src/stories/index.js
Labels: review

#34 feature/input with icon & feature/icon This closes #21, closes #35
  .prettierrc
  .storybook/preview-head.html
  .vscode/settings.json
  public/index.html
  src/Elements/Button.js
  src/Elements/Icon.js
  src/Elements/InputWithIcon.js
  src/stories/Elements/Icon.js
  src/stories/Elements/InputWithIcon.js
  src/stories/index.js
Labels: review

#35 18 feature/not found closes #18
  src/Views/NotFound.js
  src/stories/Views/NotFound.js
  src/stories/index.js
Labels: review

#37 Adds basic components List, ListItem and ListItemWithIcon closes #27
  src/Elements/List.js
  src/Elements/ListItem.js
  src/Elements/ListItemWithIcon.js
  src/assets/reset.css
  src/stories/Elements/List.js
  src/stories/index.js
Labels: review

#38 7-feature/flex container
  src/Containers/FlexContainer.js
  src/stories/Containers/FlexContainer.js
  src/stories/index.js
Labels: enhancement, review

#42 Basic Header component closes #20
  src/Components/Header.js
  src/Containers/FlexContainer.js
  src/assets/reset.css
  src/stories/Components/Header.js
  src/stories/index.js
Labels: review

#49 Refactor header component
  src/Components/Header.js
  src/Containers/FlexContainer.js
  src/Elements/List.js
Labels: review

#48 8-feature/global css theme.
  .storybook/preview-head.html
  src/Containers/FlexContainer.js
  src/Elements/Button.js
  src/Elements/Input.js
  src/Elements/Paragraph.js
  src/MainTheme.js
  src/Views/NotFound.js
  src/index.css
  src/stories/Elements/Button.js
  src/stories/Elements/Heading.js
  src/stories/Elements/Input.js
  src/withStyles.js
Labels: review

#51 Fix FlexContainer not applying align & justify properties
  src/Components/Header.js
  src/Containers/FlexContainer.js
  src/Elements/Button.js
  src/index.css
Labels: bug

#52 feature/subscription-card closes #25
  src/Components/SubscriptionCard.js
  src/Elements/Card.js
  src/Elements/Icon.js
  src/Elements/ListItemWithIcon.js
  src/stories/Components/SubscriptionCard.js
  src/stories/Elements/List.js
  src/stories/index.js
Labels: review

#56 cleanup of index.js in storybook
  src/stories/index.js
Labels: review

#53 45 feature/copy textfield closes #45
  src/Elements/CopyTextfield.js
  src/index.css
  src/stories/Elements/CopyTextfield.js
  src/stories/index.js
Labels: review

#43 feature/component fix
  src/Elements/InputWithIcon.js
  src/Elements/ListItemWithIcon.js
  src/stories/Elements/InputWithIcon.js
Labels: review

#58 47-feature/dashboard navigation
  src/Components/Navigation.js
  src/Containers/FlexContainer.js
  src/Elements/Icon.js
  src/MainTheme.js
  src/stories/Components/Navigation.js
  src/stories/index.js
  src/withStyles.js
Labels: feature, review

#39 17 feature/footer closes #17
  src/Components/Footer.js
  src/stories/Components/Footer.js
  src/stories/index.js
Labels: review

#62 Component: LoginForm closes #54
  src/Components/LoginForm.js
  src/Elements/Input.js
  src/Elements/InputWithIcon.js
  src/assets/reset.css
  src/stories/Components/LoginForm.js
  src/stories/index.js
Labels: review

#55 feature/modal closes #19
  src/Components/Modal.js
  src/stories/Components/Modal.js
  src/stories/index.js
  src/withStyles.js
Labels: feature

#69 refactor icon, add styling to inputWithIcon closes #66
  src/Elements/Icon.js
  src/Elements/InputWithIcon.js
  src/stories/Elements/Icon.js
  src/stories/Elements/InputWithIcon.js
Labels: review

#72 57-feature/react redux router. Closes #57
  package.json
  src/Containers/App.js
  src/Root.js
  src/Views/NotFound.js
  src/assets/open-box.svg
  src/index.css
  src/index.js
Labels: enhancement, review

#74 59 feature/sign up form
  src/Components/SignUpForm.js
  src/Elements/InputWithIcon.js
  src/stories/Components/SignUpForm.js
  src/stories/index.js
Labels: review

#64 refactor CopyTextfield to not use inline style
  src/Elements/CopyTextfield.js
Labels: review

#79 Component Checkbox closes #68
  src/Elements/Checkbox.js
  src/stories/Elements/Checkbox.js
Labels: review

#76 feature/join session closes #67
  src/Components/JoinSession.js
  src/stories/Components/JoinSession.js
  src/stories/index.js
Labels: review

#80 65-feature/public area. Closes #65
  public/index.html
  src/Components/Footer.js
  src/Components/Header.js
  src/Containers/App.js
  src/Containers/PublicRoot.js
  src/Elements/List.js
  src/MainTheme.js
  src/Views/LandingPage.js
  src/index.css
  src/withStyles.js
Labels: enhancement, review

#87 81 bugfix/color themes. Closes #81
  src/Elements/Button.js
  src/MainTheme.js
  src/index.css
  src/withStyles.js
Labels: bug, review

#86 Fix icons not showing up in sidebar. Closes #85
  src/Components/Navigation.js
Labels: bug, review

#89 63 feature/session item
  src/Components/SessionItem.js
  src/Components/SessionItemCard.js
  src/stories/Components/SessionItem.js
  src/stories/Components/SessionItemCard.js
  src/stories/index.js
Labels: review

#97 26 feature/dashboard. Closes #26
  src/Components/Footer.js
  src/Components/Header.js
  src/Components/JoinSession.js
  src/Components/Navigation.js
  src/Components/SessionItem.js
  src/Containers/App.js
  src/Elements/Card.js
  src/Elements/Heading.js
  src/Views/Dashboard/Dashboard.js
  src/Views/Dashboard/Profile.js
  src/Views/Dashboard/Sessions.js
  src/Views/Dashboard/Settings.js
  src/Views/Dashboard/Upgrade.js
  src/Views/LandingPage.js
  src/index.css
  src/withStyles.js
Labels: review

#102 Refactor Input closes #98
  src/Components/LoginForm.js
  src/Components/SignUpForm.js
  src/Elements/Input.js
  src/Elements/InputWithIcon.js
  src/stories/Elements/Input.js
  src/stories/Elements/InputWithIcon.js
  src/stories/index.js
Labels: review

#107 Refactor: Login Signup Icon closes #105
  package.json
  src/Components/LoginForm.js
  src/Components/SignUpForm.js
  src/Components/SubscriptionCard.js
  src/Elements/Icon.js
  src/Elements/Input.js
  src/Elements/ListItemWithIcon.js
  src/stories/Elements/Icon.js
  src/stories/Elements/List.js
Labels: review

#100 60 feature/login view
  src/Components/LoginForm.js
  src/Containers/App.js
  src/Views/Login.js
  src/stories/Views/Login.js
  src/stories/index.js
Labels: review

#101 Fixed height on sessionItem
  src/Components/SessionItem.js
  src/Views/Dashboard/Sessions.js
Labels: review

#106 Updates Socket Client-testing
  src/Views/Client.js
Labels: review

#111 Adds basic redux setup and login view functionality
  src/Components/Header.js
  src/Components/LoginForm.js
  src/Root.js
  src/Views/Login.js
  src/redux/auth/actions.js
  src/redux/auth/authReducer.js
  src/redux/auth/constants.js
  src/redux/index.js
Labels: review

#114 updated gitignore
  .gitignore
Labels: review

#94 feature/session wizard this closes #82 also adds feature/loader this closes #115
  src/Components/CreateSession/Name.js
  src/Components/CreateSession/Preferences.js
  src/Components/CreateSession/SessionStarted.js
  src/Components/JoinSession.js
  src/Components/Modal.js
  src/Components/Wizard.js
  src/Containers/App.js
  src/Elements/Checkbox.js
  src/Elements/CopyTextfield.js
  src/Elements/Icon.js
  src/Elements/Loader.js
  src/Views/CreateSession.js
  src/index.css
  src/stories/Components/Wizard.js
  src/stories/Elements/Loader.js
  src/stories/index.js
Labels: review

#122 Adds dummy vote to Socket Client View
  src/Views/Client.js
Labels: review

#95 view/sign up closes #61
  src/Components/SignUpForm.js
  src/Containers/App.js
  src/Views/SignUp.js
Labels: review

#125 83-feature/presenter view
  package.json
  src/Containers/App.js
  src/Containers/FlexContainer.js
  src/Elements/CopyTextfield.js
  src/Elements/Heading.js
  src/Views/Client.js
  src/Views/LiveSessionHost/Engagement.js
  src/Views/LiveSessionHost/LiveSessionHost.js
  src/Views/LiveSessionHost/Lobby.js
  src/Views/LiveSessionHost/Timer.js
  src/Views/LiveSessionHost/Warning.js
  src/index.css
  src/redux/session/actions.js
  src/redux/session/constants.js
  src/redux/session/sessionReducer.js
  src/withStyles.js
Labels: feature, review

#120 fixed verticalalign and padding on icons closes #119
  src/Elements/Icon.js
Labels: review
